### ISSUE TITLE
gray fails with autoflake >= 1.5

### ISSUE THREAD

**Issue by alvassin** [dizballanze/gray#19]
Code that is used from autoflake in gray [has changed](https://github.com/PyCQA/autoflake/blob/v1.4/autoflake.py#L811).

From 1.5 version, args are expected to [be dict](https://github.com/PyCQA/autoflake/blob/v1.7.0/autoflake.py#L901).

Steps to reproduce:
```bash
mkdir gray-test
cd $_
python3.9 -m venv env
. env/bin/activate
touch example.py
gray example.py

Failed to reformat file "example.py"
Traceback (most recent call last):
  File ".../gray-test/env/lib/python3.9/site-packages/gray/processing.py", line 124, in worker
    fade_file(fname, formatter)
  File ".../gray-test/env/lib/python3.9/site-packages/gray/processing.py", line 114, in fade_file
    formatter.process(file_path)
  File ".../gray-test/env/lib/python3.9/site-packages/gray/formatters/composite.py", line 16, in process
    formatter.process(file_path)
  File ".../gray-test/env/lib/python3.9/site-packages/gray/formatters/autoflake.py", line 25, in process
    fix_file(file_path, args=self._args, standard_out=sys.stdout)
  File ".../gray-test/env/lib/python3.9/site-packages/autoflake.py", line 901, in fix_file
    args["write_to_stdout"],
TypeError: 'Namespace' object is not subscriptable
[T:MainThread] ERROR:gray.processing: Failed when processing "example.py"
```

**Comment by dizballanze** [comment]
Feel free to open a PR :)
